/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness plus optional services, reported as optional (never failure).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hospital/baseline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hospital Baseline
         * @description The SYNTHETIC baseline hospital configuration.
         */
        get: operations["hospital_baseline_api_v1_hospital_baseline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Model Card
         * @description Model card: purpose, scope, honest limitations (B1).
         */
        get: operations["model_card_api_v1_model_card_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scenarios
         * @description Presets and validated ranges for the Scenario Lab UI (B9).
         */
        get: operations["scenarios_api_v1_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Weather
         * @description Weather source status. The default demo weather is SYNTHETIC_PROFILE;
         *     live Open-Meteo is optional and labelled REAL WEATHER when used.
         */
        get: operations["weather_api_v1_weather_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Simulation */
        post: operations["create_simulation_api_v1_simulations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comparisons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Comparison */
        post: operations["create_comparison_api_v1_comparisons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_v1_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessIn */
        AccessIn: {
            /**
             * Start Hour
             * @default 18
             */
            start_hour: number;
            /**
             * Duration Hours
             * @default 24
             */
            duration_hours: number;
            /**
             * Staff Access Fraction
             * @default 0.6
             */
            staff_access_fraction: number;
            /**
             * Delivery Fraction
             * @default 0.25
             */
            delivery_fraction: number;
            /**
             * Arrival Multiplier
             * @default 1.4
             */
            arrival_multiplier: number;
        };
        /** AccessRow */
        AccessRow: {
            /**
             * Staff Access Fraction
             * @default 1
             */
            staff_access_fraction: number;
            /**
             * Delivery Fraction
             * @default 1
             */
            delivery_fraction: number;
            /**
             * Arrival Multiplier
             * @default 1
             */
            arrival_multiplier: number;
        } & {
            [key: string]: unknown;
        };
        /** AlertEpisode */
        AlertEpisode: {
            /** Rule Id */
            rule_id: string;
            /** Rule Text */
            rule_text: string;
            /** Severity */
            severity: string;
            /** Metric */
            metric: string;
            /** Unit */
            unit: string;
            /** Observed Peak */
            observed_peak: number;
            /** Threshold */
            threshold: number;
            /** First Hour */
            first_hour: number;
            /** Last Hour */
            last_hour: number;
            /** Duration Hours */
            duration_hours: number;
            /** Affected Variable */
            affected_variable: string;
        } & {
            [key: string]: unknown;
        };
        /** AttributionEntry */
        AttributionEntry: {
            /** Intervention */
            intervention: string;
            /** Detail */
            detail: Record<string, never>;
            /** Deltas */
            deltas: {
                [key: string]: components["schemas"]["MetricDelta"] | {
                    [key: string]: components["schemas"]["MetricDelta"];
                };
            };
            /** Explanation */
            explanation: string;
        } & {
            [key: string]: unknown;
        };
        /** BackupIn */
        BackupIn: {
            /**
             * Generator Availability Fraction
             * @default 1
             */
            generator_availability_fraction: number;
        };
        /** ComparisonRequest */
        ComparisonRequest: {
            /**
             * Scenario
             * @enum {string}
             */
            scenario: "normal_operations" | "heatwave_power_stress" | "heatwave_power_outage" | "flood_storm_access";
            /**
             * Duration Hours
             * @default 72
             */
            duration_hours: number;
            weather?: components["schemas"]["WeatherIn"];
            stress?: components["schemas"]["StressIn"];
            outage?: components["schemas"]["OutageIn"] | null;
            access?: components["schemas"]["AccessIn"] | null;
            backup?: components["schemas"]["BackupIn"];
            interventions?: components["schemas"]["InterventionsIn"] | null;
            /**
             * Stochastic
             * @default false
             */
            stochastic: boolean;
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /** ComparisonResponse */
        ComparisonResponse: {
            /** Model Version */
            model_version: string;
            /** Input Hash */
            input_hash: string;
            /** Seed */
            seed: number;
            baseline: components["schemas"]["SimulationResponse"];
            treatment: components["schemas"]["SimulationResponse"];
            /** Deltas */
            deltas: Record<string, never>;
            /** Key Metric Deltas */
            key_metric_deltas: Record<string, never>;
            /** Attribution */
            attribution: components["schemas"]["AttributionEntry"][];
            /** Explanations */
            explanations: string[];
        } & {
            [key: string]: unknown;
        };
        /** FailurePoint */
        FailurePoint: {
            /** Rank */
            rank: number;
            /** Resource */
            resource: string;
            /** Rule Id */
            rule_id: string;
            /** First Hour */
            first_hour: number;
            /** Last Hour */
            last_hour: number;
            /** Peak Severity */
            peak_severity: string;
            /** Margin Trace */
            margin_trace: components["schemas"]["MarginPoint"][];
            /** Explanation */
            explanation: string;
            /** Cascade Parent */
            cascade_parent?: string | null;
            /**
             * Cascade Children
             * @default []
             */
            cascade_children: string[];
        } & {
            [key: string]: unknown;
        };
        /** FirstFailure */
        FirstFailure: {
            /** Rule Id */
            rule_id: string;
            /** Hour */
            hour: number;
            /** Resource */
            resource: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HourRow */
        HourRow: {
            /** Hour */
            hour: number;
            /** Temperature C */
            temperature_c?: number | null;
            /** Grid Fraction */
            grid_fraction: number;
            power: components["schemas"]["PowerRow"];
            /** Staffing */
            staffing: {
                [key: string]: components["schemas"]["StaffingRow"];
            };
            /** Units */
            units: {
                [key: string]: components["schemas"]["UnitRow"];
            };
            /**
             * Supplies
             * @default {}
             */
            supplies: {
                [key: string]: components["schemas"]["SupplyRow"];
            };
            /**
             * @default {
             *       "staff_access_fraction": 1,
             *       "delivery_fraction": 1,
             *       "arrival_multiplier": 1
             *     }
             */
            access: components["schemas"]["AccessRow"];
            /** Ed */
            ed: {
                [key: string]: number;
            };
            /**
             * Discharged
             * @default 0
             */
            discharged: number;
            /** Binding Constraint */
            binding_constraint: string;
            /** Margins */
            margins?: {
                [key: string]: number;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** InterventionsIn */
        InterventionsIn: {
            /** Activate Surge Beds */
            activate_surge_beds?: components["schemas"]["SurgeIn"][];
            /** Reallocate Staff */
            reallocate_staff?: components["schemas"]["StaffMoveIn"][];
            /** Reduce Noncritical Load Kw */
            reduce_noncritical_load_kw?: components["schemas"]["ShedIn"][];
            /** Recall Staff */
            recall_staff?: components["schemas"]["RecallIn"][];
            /** Emergency Resupply */
            emergency_resupply?: components["schemas"]["ResupplyIn"][];
        };
        /** MarginPoint */
        MarginPoint: {
            /** Hour */
            hour: number;
            /** Margin */
            margin: number;
        } & {
            [key: string]: unknown;
        };
        /** MetricDelta */
        MetricDelta: {
            /** Absolute */
            absolute: number;
            /** Relative */
            relative?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** OutageIn */
        OutageIn: {
            /**
             * Start Hour
             * @default 24
             */
            start_hour: number;
            /**
             * Duration Hours
             * @default 36
             */
            duration_hours: number;
            /**
             * Grid Fraction
             * @default 0
             */
            grid_fraction: number;
        };
        /** PlanRequest */
        PlanRequest: {
            /**
             * Scenario
             * @enum {string}
             */
            scenario: "normal_operations" | "heatwave_power_stress" | "heatwave_power_outage" | "flood_storm_access";
            /**
             * Duration Hours
             * @default 72
             */
            duration_hours: number;
            weather?: components["schemas"]["WeatherIn"];
            stress?: components["schemas"]["StressIn"];
            outage?: components["schemas"]["OutageIn"] | null;
            access?: components["schemas"]["AccessIn"] | null;
            backup?: components["schemas"]["BackupIn"];
            interventions?: components["schemas"]["InterventionsIn"] | null;
            /**
             * Stochastic
             * @default false
             */
            stochastic: boolean;
            /**
             * Seed
             * @default 42
             */
            seed: number;
            objective?: components["schemas"]["PlannerObjectiveIn"];
            budget?: components["schemas"]["PlannerBudgetIn"];
        };
        /** PlanResponse */
        PlanResponse: {
            /** Model Version */
            model_version: string;
            /** Input Hash */
            input_hash: string;
            /** Seed */
            seed: number;
            /** Label */
            label: string;
            /** Action Plan */
            action_plan: components["schemas"]["PlanStep"][];
            /** Score */
            score: Record<string, never>;
            /** References */
            references: components["schemas"]["ReferencePlan"][];
            /** Search Stats */
            search_stats: Record<string, never>;
            /** Failure Points Before */
            failure_points_before: components["schemas"]["FailurePoint"][];
            /** Failure Points After */
            failure_points_after: components["schemas"]["FailurePoint"][];
            /** Assumptions */
            assumptions: string[];
            provenance: components["schemas"]["Provenance"];
            /** Limitations */
            limitations: string[];
        } & {
            [key: string]: unknown;
        };
        /** PlanStep */
        PlanStep: {
            /** Action */
            action: string;
            /** Detail */
            detail: Record<string, never>;
            /** Start Hour */
            start_hour: number;
            /** Effective Hour */
            effective_hour: number;
            /** Marginal Gain Resilience */
            marginal_gain_resilience: number | null;
            /** Resilience Index */
            resilience_index: number;
            /** Reason */
            reason: string;
        } & {
            [key: string]: unknown;
        };
        /** PlannerBudgetIn */
        PlannerBudgetIn: {
            /**
             * Max Simulations
             * @default 600
             */
            max_simulations: number;
            /**
             * Max Seconds
             * @default 5
             */
            max_seconds: number;
            /**
             * Max Actions
             * @default 5
             */
            max_actions: number;
            /**
             * Grid Hours
             * @default 3
             */
            grid_hours: number;
        };
        /** PlannerObjectiveIn */
        PlannerObjectiveIn: {
            /**
             * Lambda Burden
             * @default 0.5
             */
            lambda_burden: number;
        };
        /** PowerRow */
        PowerRow: {
            /** Demand Kw */
            demand_kw: number;
            /** Grid Supply Kw */
            grid_supply_kw: number;
            /** Gen Output Kw */
            gen_output_kw: number;
            /** Available Supply Kw */
            available_supply_kw: number;
            /** Deficit Kw */
            deficit_kw: number;
            /** Reserve Kw */
            reserve_kw: number;
            /** Critical At Risk Kw */
            critical_at_risk_kw: number;
            /** Critical Demand Kw */
            critical_demand_kw: number;
            /** Shed Kw */
            shed_kw: number;
            /** Fuel L */
            fuel_l: number;
        } & {
            [key: string]: unknown;
        };
        /** Provenance */
        Provenance: {
            /**
             * Hospital Data
             * @default SYNTHETIC
             */
            hospital_data: string;
            /**
             * Weather
             * @default SYNTHETIC_PROFILE
             */
            weather: string;
            /**
             * Outputs
             * @default CALCULATED
             */
            outputs: string;
            /** Model Version */
            model_version: string;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        } & {
            [key: string]: unknown;
        };
        /** RecallIn */
        RecallIn: {
            /**
             * Unit
             * @enum {string}
             */
            unit: "ed" | "ward" | "icu";
            /** Nurses */
            nurses: number;
            /** Start Hour */
            start_hour: number;
        };
        /** ReferencePlan */
        ReferencePlan: {
            /** Name */
            name: string;
            /** Resilience Index */
            resilience_index: number | null;
            /** Actions */
            actions: string[];
        } & {
            [key: string]: unknown;
        };
        /** ResupplyIn */
        ResupplyIn: {
            /**
             * Fuel L
             * @default 0
             */
            fuel_l: number;
            /** Items */
            items?: {
                [key: string]: number;
            };
            /**
             * Start Hour
             * @default 0
             */
            start_hour: number;
        };
        /** ScenarioInfo */
        ScenarioInfo: {
            /** Model Version */
            model_version: string;
            /** Presets */
            presets: Record<string, never>;
            /** Ranges */
            ranges: Record<string, never>;
            /** Assumptions */
            assumptions: string[];
            /** Limitations */
            limitations: string[];
        } & {
            [key: string]: unknown;
        };
        /** ShedIn */
        ShedIn: {
            /** Kw */
            kw: number;
            /** Start Hour */
            start_hour: number;
            /** End Hour */
            end_hour: number;
        };
        /** SimulationRequest */
        SimulationRequest: {
            /**
             * Scenario
             * @enum {string}
             */
            scenario: "normal_operations" | "heatwave_power_stress" | "heatwave_power_outage" | "flood_storm_access";
            /**
             * Duration Hours
             * @default 72
             */
            duration_hours: number;
            weather?: components["schemas"]["WeatherIn"];
            stress?: components["schemas"]["StressIn"];
            outage?: components["schemas"]["OutageIn"] | null;
            access?: components["schemas"]["AccessIn"] | null;
            backup?: components["schemas"]["BackupIn"];
            interventions?: components["schemas"]["InterventionsIn"] | null;
            /**
             * Stochastic
             * @default false
             */
            stochastic: boolean;
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /** SimulationResponse */
        SimulationResponse: {
            /** Run Id */
            run_id: string;
            /** Model Version */
            model_version: string;
            /** Input Hash */
            input_hash: string;
            /** Seed */
            seed: number;
            /** Stochastic */
            stochastic: boolean;
            summary: components["schemas"]["Summary"];
            /** Series */
            series: components["schemas"]["HourRow"][];
            /** Alerts */
            alerts: components["schemas"]["AlertEpisode"][];
            /** Failure Points */
            failure_points: components["schemas"]["FailurePoint"][];
            /** Assumptions */
            assumptions: string[];
            provenance: components["schemas"]["Provenance"];
            /** Limitations */
            limitations: string[];
        } & {
            [key: string]: unknown;
        };
        /** StaffMoveIn */
        StaffMoveIn: {
            /**
             * From Unit
             * @enum {string}
             */
            from_unit: "ed" | "ward" | "icu";
            /**
             * To Unit
             * @enum {string}
             */
            to_unit: "ed" | "ward" | "icu";
            /** Nurses */
            nurses: number;
            /** Start Hour */
            start_hour: number;
        };
        /** StaffingRow */
        StaffingRow: {
            /** Available */
            available: number;
            /** Staffed Capacity */
            staffed_capacity: number;
            /** Required */
            required: number;
            /** Shortfall */
            shortfall: number;
        } & {
            [key: string]: unknown;
        };
        /** StressIn */
        StressIn: {
            /**
             * Arrival Multiplier
             * @default 1.25
             */
            arrival_multiplier: number;
            /**
             * Los Multiplier
             * @default 1
             */
            los_multiplier: number;
            /**
             * Staff Availability Fraction
             * @default 0.9
             */
            staff_availability_fraction: number;
            /**
             * Power Supply Fraction
             * @default 0.8
             */
            power_supply_fraction: number;
        };
        /** Summary */
        Summary: {
            /** Peak Ward Occupancy Pct */
            peak_ward_occupancy_pct?: number | null;
            /** Peak Icu Occupancy Pct */
            peak_icu_occupancy_pct?: number | null;
            /** Peak Ed Occupancy Pct */
            peak_ed_occupancy_pct?: number | null;
            /** Hours Ward Above Threshold */
            hours_ward_above_threshold: number;
            /** Hours Icu Above Threshold */
            hours_icu_above_threshold: number;
            /** Peak Ed Waiting */
            peak_ed_waiting: number;
            /** Peak Ed Boarding */
            peak_ed_boarding: number;
            /** Overflow Patient Hours */
            overflow_patient_hours: number;
            /** Staff Shortfall Nurse Hours */
            staff_shortfall_nurse_hours: number;
            /** Hours Beds Over Usable */
            hours_beds_over_usable: number;
            /** Peak Power Demand Kw */
            peak_power_demand_kw: number;
            /** Hours Power Deficit */
            hours_power_deficit: number;
            /** Peak Power Deficit Kw */
            peak_power_deficit_kw: number;
            /** Energy Unserved Kwh */
            energy_unserved_kwh: number;
            /** Min Power Reserve Kw */
            min_power_reserve_kw: number;
            /** Hours Critical Load At Risk */
            hours_critical_load_at_risk: number;
            /** Fuel Remaining L */
            fuel_remaining_l: number;
            /** Hours To Fuel Exhaustion */
            hours_to_fuel_exhaustion?: number | null;
            /** Resilience Index */
            resilience_index: number;
            first_failure?: components["schemas"]["FirstFailure"] | null;
            /** Time To First Failure Hours */
            time_to_first_failure_hours?: number | null;
            /**
             * Root Failures
             * @default 0
             */
            root_failures: number;
            /**
             * Cascade Children
             * @default 0
             */
            cascade_children: number;
        } & {
            [key: string]: unknown;
        };
        /** SupplyRow */
        SupplyRow: {
            /** Stock */
            stock: number;
            /** Delivered */
            delivered: number;
            /** Consumption */
            consumption: number;
            /**
             * Unmet
             * @default 0
             */
            unmet: number;
            /** Cover Hours */
            cover_hours?: number | null;
            /**
             * Stockout
             * @default false
             */
            stockout: boolean;
        } & {
            [key: string]: unknown;
        };
        /** SurgeIn */
        SurgeIn: {
            /**
             * Unit
             * @enum {string}
             */
            unit: "ed" | "ward" | "icu";
            /** Beds */
            beds: number;
            /** Start Hour */
            start_hour: number;
        };
        /** UnitRow */
        UnitRow: {
            /** Open Beds */
            open_beds: number;
            /** Usable Beds */
            usable_beds: number;
            /** Occupied */
            occupied: number;
            /** Available Beds */
            available_beds: number;
            /** Occupancy Pct */
            occupancy_pct: number | null;
            /** Beds Over Usable */
            beds_over_usable: number;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeatherIn */
        WeatherIn: {
            /**
             * Mode
             * @default synthetic_profile
             * @constant
             */
            mode: "synthetic_profile";
            /**
             * Max Temperature C
             * @default 41
             */
            max_temperature_c: number;
            /** Min Temperature C */
            min_temperature_c?: number | null;
            /**
             * Humidity Pct
             * @default 55
             */
            humidity_pct: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    hospital_baseline_api_v1_hospital_baseline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    model_card_api_v1_model_card_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    scenarios_api_v1_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioInfo"];
                };
            };
        };
    };
    weather_api_v1_weather_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    create_simulation_api_v1_simulations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_comparison_api_v1_comparisons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_api_v1_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
